[package]
name = "ag-lcd"
version = "0.1.0"
authors = ["Michael House <mjhouse@protonmail.com>"]
keywords = [ "arduino", "atmega328p", "avr-hal", "lcd", "HD44780", "LiquidCrystal" ]
categories = ["embedded","hardware-support"]
description = "A rust port of the LiquidCrystal arduino library"
homepage = "https://github.com/mjhouse/ag-lcd"
documentation = "https://mjhouse.github.io/ag-lcd/"
repository = "https://github.com/mjhouse/ag-lcd"
license = "GPL-3.0-or-later"
edition = "2018"
readme = "README.md"


[dependencies]
ufmt = "0.1.0"

[dev-dependencies]
panic-halt = "0.2.0"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "ac72adbe6db8900c41681b759ff62a11f2915916"

[dependencies.avr-hal-generic]
git = "https://github.com/rahix/avr-hal"
rev = "ac72adbe6db8900c41681b759ff62a11f2915916"

[dev-dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "ac72adbe6db8900c41681b759ff62a11f2915916"
features = ["arduino-nano"]

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"